apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  version: v1.19.1
  chart: cert-manager
  repo: https://charts.jetstack.io
  valuesContent: |-
    crds:
      enabled: true