---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: longhorn-demo
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint
  namespace: longhorn-demo
data:
  entrypoint.sh: |
    #!/bin/sh
    [ -f /usr/share/nginx/html/index.html ] || echo "<h1>Hello world!</h1>" >> /usr/share/nginx/html/index.html
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: longhorn-demo
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.27
        livenessProbe:
          exec:
            command:
              - ls
              - /usr/share/nginx/html/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: hello
        image: busybox:stable
        command:
        - /scripts/entrypoint.sh
        volumeMounts:
        - name: entrypoint
          mountPath: /scripts
        - name: www
          mountPath: /usr/share/nginx/html
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint
          defaultMode: 0755
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 1Gi