# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: longhorn-webdata-pvc
#   namespace: longhorn-demo
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 2Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: webpage
#   namespace: longhorn-demo
#   labels:
#     app: webpage
# spec:
#   ports:
#   - port: 80
#     name: web
#   selector:
#     app: webpage
#   type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: webpage
  namespace: longhorn-demo
  labels:
    app: webpage
spec:
  restartPolicy: Always
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
          - ls
          - /usr/share/nginx/html/lost+found
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: webdata
      mountPath: /usr/share/nginx/html
    ports:
    - containerPort: 80
  volumes:
  - name: webdata
    persistentVolumeClaim:
      claimName: longhorn-webdata-pvc